"""Query-time and harvest web gap-fill.

Search uses keyword queries — never a raw URL as the search string.
Tavily is preferred when an API key is set. Otherwise a single ddgs engine
(DuckDuckGo) is used. ``backend=\"auto\"`` and ``backend=\"google\"`` are
never used: in ddgs 9.x Google is disabled, and requesting it silently fans
out to Yahoo, Brave, Startpage, and Mojeek.

Wikipedia, search-engine SERP hosts, and Gemini/AI-overview rows are dropped;
remaining hits are ranked and the best kept.
"""
from __future__ import annotations

import re
import threading
import time
from typing import Any
from urllib.parse import urlparse

from ..config import Settings
from ..logging import get_logger
from .lexical import should_use_web

log = get_logger(__name__)

# Dedupe identical queries within one process run (harvesting regenerates the
# same/near-same keyword queries many times per technology).
_QUERY_CACHE: dict[str, list[dict[str, Any]]] = {}
_QUERY_CACHE_LOCK = threading.Lock()

# Harvesting can fan out many concurrent search_web() calls from a thread
# pool. Without a client-side cap, a burst of simultaneous requests can
# overwhelm the local SearXNG container's worker count (and, on Windows,
# Docker Desktop's port-forwarding proxy), producing "connection reset by
# peer" / "server disconnected" before the request ever reaches SearXNG.
_SEARXNG_CONCURRENCY = 3
_searxng_semaphore = threading.Semaphore(_SEARXNG_CONCURRENCY)

# Space out requests per scraping backend so a burst of harvest queries never
# hammers an engine into a 429/403/captcha response.
_MIN_INTERVAL_S = 3.0
_last_call_at: dict[str, float] = {}
_rate_limit_lock = threading.Lock()


def _throttle(backend: str) -> None:
    with _rate_limit_lock:
        now = time.monotonic()
        wait = _last_call_at.get(backend, 0.0) + _MIN_INTERVAL_S - now
        if wait > 0:
            time.sleep(wait)
        _last_call_at[backend] = time.monotonic()

_URL_RE = re.compile(r"https?://[^\s<>\"']+", re.IGNORECASE)

_GENERIC_TOKENS = {
    "http", "https", "www", "html", "htm", "php", "aspx", "jsp",
    "index", "docs", "documentation", "reference", "current", "latest",
    "en-us", "en", "us", "api", "javase", "javaee",
    "com", "org", "io", "net", "edu",
}

_SKIP_HOST_MARKERS = (
    "wikipedia.org",
    "wikiwand.com",
    "grokipedia.com",
    "yahoo.com",
    "search.yahoo.com",
    "answers.yahoo.com",
    "bing.com",
    "duckduckgo.com",
    "startpage.com",
    "brave.com",
    "search.brave.com",
    "mojeek.com",
    "yandex.com",
    "yandex.ru",
    "facebook.com",
    "twitter.com",
    "x.com",
    "pinterest.com",
    "reddit.com",
    "quora.com",
)

# Engines we will actually query, in preference order. Never "auto" / "all" /
# "google": Google is disabled in ddgs>=9 and an unknown backend falls back to
# every remaining engine (Yahoo, Brave, Startpage, Mojeek, Wikipedia, …).
# DuckDuckGo is listed first for quality but is blocked on some corporate
# networks; Brave/Startpage/Mojeek are free, keyless scraping fallbacks.
_DDGS_BACKENDS = ("duckduckgo", "brave", "startpage", "mojeek")

_GEMINI_HOST_MARKERS = (
    "gemini.google.com",
    "bard.google.com",
    "vertexaisearch.cloud.google.com",
    "google.com/search",
    "g.co/gemini",
)

_GEMINI_TEXT_MARKERS = (
    "ai overview",
    "generated by gemini",
    "gemini generated",
    "google gemini",
    "generative ai is experimental",
    "gemini said",
)

_PREFERRED_DOC_HOSTS = (
    "docs.spring.io",
    "spring.io",
    "docs.oracle.com",
    "openjdk.org",
    "learn.microsoft.com",
    "docs.microsoft.com",
    "jakarta.ee",
    "docs.python.org",
    "projectreactor.io",
    "kafka.apache.org",
    "hibernate.org",
    "micrometer.io",
    "resilience4j.readme.io",
    "github.com/spring-projects",
    "baeldung.com",
    "stackoverflow.com",
    "medium.com",
    "dev.to",
    "javatpoint.com",
    "geeksforgeeks.org",
)


def to_search_keywords(text: str) -> str:
    """Turn a URL or mixed query into space-separated search keywords."""
    raw = (text or "").strip()
    if not raw:
        return ""
    chunks: list[str] = []
    for url in _URL_RE.findall(raw):
        chunks.append(_keywords_from_url(url))
    leftover = _URL_RE.sub(" ", raw)
    leftover = leftover.replace("://", " ").replace("/", " ").replace("-", " ").replace("_", " ")
    leftover = leftover.replace(".", " ")
    chunks.append(leftover)
    tokens: list[str] = []
    seen: set[str] = set()
    for chunk in chunks:
        for tok in re.split(r"[^A-Za-z0-9@]+", chunk):
            if not tok:
                continue
            key = tok.lower()
            if len(key) < 2 or key in _GENERIC_TOKENS or key.isdigit() or key in seen:
                continue
            seen.add(key)
            tokens.append(tok if tok.startswith("@") else key)
    return " ".join(tokens)


def documentation_query(*parts: str) -> str:
    """Keyword query for official-tech documentation, never a raw URL."""
    merged = " ".join(to_search_keywords(p) for p in parts if p)
    keywords = to_search_keywords(merged)
    if not keywords:
        return ""
    if "documentation" not in keywords.split():
        keywords = f"{keywords} documentation"
    return keywords


def is_unusable_hit(url: str, title: str = "", snippet: str = "") -> bool:
    """Return True if a search hit is junk (Gemini/AI-overview noise, blocked hosts, etc.)."""
    host = urlparse(url).netloc.lower()
    path = (urlparse(url).path or "").lower()
    blob = f"{url} {title} {snippet}".lower()
    if any(m in host or m in url.lower() for m in _SKIP_HOST_MARKERS):
        return True
    if any(m in url.lower() or m in path for m in _GEMINI_HOST_MARKERS):
        return True
    if host.endswith("google.com") and ("/search" in path or "gemini" in blob):
        return True
    if any(m in blob for m in _GEMINI_TEXT_MARKERS):
        return True
    return False


def filter_search_hits(hits: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Drop duplicate/unusable URLs from a list of search hits."""
    out = []
    seen: set[str] = set()
    for hit in hits:
        url = (hit.get("url") or "").strip()
        if not url or url in seen:
            continue
        if is_unusable_hit(url, hit.get("title") or "", hit.get("snippet") or ""):
            continue
        seen.add(url)
        out.append(hit)
    return out


def rank_search_hits(
    hits: list[dict[str, Any]],
    *,
    keywords: str = "",
    preferred_host: str = "",
) -> list[dict[str, Any]]:
    """Best-first: preferred/official docs, then keyword overlap, never junk hosts."""
    cleaned = filter_search_hits(hits)
    terms = [t for t in to_search_keywords(keywords).split() if t != "documentation"]

    def score(hit: dict[str, Any]) -> tuple[int, int, int]:
        url = hit.get("url") or ""
        title = (hit.get("title") or "").lower()
        host = urlparse(url).netloc.lower()
        host_rank = 2
        if preferred_host and (host == preferred_host.lower() or host.endswith("." + preferred_host.lower())):
            host_rank = 0
        elif any(host == h or host.endswith("." + h) or h in url.lower() for h in _PREFERRED_DOC_HOSTS):
            host_rank = 1
        overlap = 0
        hay = f"{title} {url.lower()}"
        for t in terms:
            if t.lower() in hay:
                overlap += 1
        return (host_rank, -overlap, 0)

    return sorted(cleaned, key=score)


def search_web(query: str, settings: Settings, *, limit: int = 5) -> list[dict[str, Any]]:
    """Return ranked snippet hits (Tavily/Brave API, then ddgs scraping — never auto)."""
    keywords = to_search_keywords(query)
    if not keywords:
        return []
    fetch = max(limit * 4, 12)
    cache_key = f"{fetch}:{keywords}"
    with _QUERY_CACHE_LOCK:
        cached = _QUERY_CACHE.get(cache_key)
    if cached is not None:
        return rank_search_hits(cached, keywords=keywords)[:limit]
    hits: list[dict[str, Any]] = []
    if getattr(settings, "tavily_api_key", None):
        hits = _tavily(keywords, settings, limit=fetch)
    if len(filter_search_hits(hits)) < limit and getattr(settings, "brave_api_key", None):
        hits = hits + _brave_api(keywords, settings, limit=fetch)
    if len(filter_search_hits(hits)) < limit and getattr(settings, "searxng_url", None):
        hits = hits + _searxng_text(keywords, settings, limit=fetch)
    if len(filter_search_hits(hits)) < limit:
        hits = hits + _ddgs_text(keywords, limit=fetch)
    with _QUERY_CACHE_LOCK:
        _QUERY_CACHE[cache_key] = hits
    ranked = rank_search_hits(hits, keywords=keywords)
    return ranked[:limit]


def _keywords_from_url(url: str) -> str:
    parsed = urlparse(url)
    host = parsed.netloc.lower().removeprefix("www.")
    host_words = host.replace(".", " ")
    path = parsed.path.replace("-", " ").replace("_", " ").replace("/", " ")
    return f"{host_words} {path}"


def _tavily(query: str, settings: Settings, *, limit: int) -> list[dict[str, Any]]:
    try:
        import httpx
        resp = httpx.post(
            "https://api.tavily.com/search",
            json={
                "api_key": settings.tavily_api_key,
                "query": query,
                "max_results": limit,
                "search_depth": "basic",
            },
            timeout=12.0,
        )
        resp.raise_for_status()
        data = resp.json()
        out = []
        for r in data.get("results") or []:
            url = r.get("url") or ""
            out.append({
                "title": r.get("title") or "",
                "url": url,
                "snippet": r.get("content") or r.get("snippet") or "",
            })
        return out
    except Exception as exc:
        log.warning("tavily_search_failed", error=str(exc))
        return []


def _brave_api(query: str, settings: Settings, *, limit: int) -> list[dict[str, Any]]:
    """Official Brave Search API (keyless scraping of search.brave.com is not this)."""
    try:
        import httpx
        resp = httpx.get(
            "https://api.search.brave.com/res/v1/web/search",
            params={"q": query, "count": min(limit, 20)},
            headers={
                "Accept": "application/json",
                "X-Subscription-Token": settings.brave_api_key,
            },
            timeout=12.0,
        )
        resp.raise_for_status()
        data = resp.json()
        out = []
        for r in (data.get("web") or {}).get("results") or []:
            out.append({
                "title": r.get("title") or "",
                "url": r.get("url") or "",
                "snippet": r.get("description") or "",
            })
        return out
    except Exception as exc:
        log.warning("brave_api_search_failed", error=str(exc))
        return []


def _searxng_text(query: str, settings: Settings, *, limit: int) -> list[dict[str, Any]]:
    """Self-hosted, open-source SearXNG (free, no API key, no external rate limit)."""
    base = (settings.searxng_url or "").rstrip("/")
    if not base:
        return []
    try:
        import httpx
    except Exception:
        return []
    last_exc: Exception | None = None
    with _searxng_semaphore:
        for attempt in range(2):
            try:
                resp = httpx.get(
                    f"{base}/search",
                    params={"q": query, "format": "json", "pageno": 1},
                    headers={"Accept": "application/json"},
                    timeout=30.0,
                )
                resp.raise_for_status()
                data = resp.json()
                out = []
                for r in (data.get("results") or [])[:limit]:
                    out.append({
                        "title": r.get("title") or "",
                        "url": r.get("url") or "",
                        "snippet": r.get("content") or "",
                    })
                return out
            except Exception as exc:
                last_exc = exc
    log.warning("searxng_search_failed", error=str(last_exc))
    return []


def _enabled_ddgs_text_backends() -> set[str]:
    try:
        from ddgs.engines import ENGINES
        return set((ENGINES.get("text") or {}).keys())
    except Exception:
        return set()


def _ddgs_backends() -> list[str]:
    enabled = _enabled_ddgs_text_backends()
    candidates = [n for n in _DDGS_BACKENDS if not enabled or n in enabled]
    if not candidates:
        log.warning(
            "ddgs_backend_unavailable",
            wanted=_DDGS_BACKENDS,
            enabled=sorted(enabled),
        )
    return candidates


def _ddgs_text(query: str, *, limit: int) -> list[dict[str, Any]]:
    try:
        from ddgs import DDGS
    except Exception:
        log.warning("ddgs_unavailable", hint="pip install ddgs")
        return []
    # Try each backend in order (e.g. duckduckgo blocked on some networks)
    # and stop at the first one that actually returns hits. Throttled per
    # backend so a burst of harvest queries doesn't trigger 429/403/captcha.
    for backend in _ddgs_backends():
        _throttle(backend)
        try:
            with DDGS() as client:
                raw = list(client.text(query, max_results=limit, backend=backend))
            out = []
            for r in raw:
                url = r.get("href") or r.get("url") or ""
                out.append({
                    "title": r.get("title") or "",
                    "url": url,
                    "snippet": r.get("body") or r.get("snippet") or "",
                })
            if out:
                return out
        except Exception as exc:
            log.warning("ddgs_search_failed", backend=backend, error=str(exc))
    return []


__all__ = [
    "documentation_query",
    "filter_search_hits",
    "is_unusable_hit",
    "rank_search_hits",
    "search_web",
    "should_use_web",
    "to_search_keywords",
]
