"""Keyword web search helpers (no network)."""
from __future__ import annotations

import pytest

from mcp_kb.retrieval.web_search import (
    documentation_query,
    filter_search_hits,
    is_unusable_hit,
    rank_search_hits,
    to_search_keywords,
)


@pytest.fixture(autouse=True)
def _clear_search_cache():
    from mcp_kb.retrieval import web_search
    web_search._QUERY_CACHE.clear()
    web_search._last_call_at.clear()
    yield
    web_search._QUERY_CACHE.clear()
    web_search._last_call_at.clear()


def test_url_becomes_keywords_not_the_url():
    q = to_search_keywords(
        "https://docs.spring.io/spring-framework/reference/core/beans.html"
    )
    assert "https://" not in q
    assert "spring" in q
    assert "beans" in q
    assert "docs.spring.io" not in q


def test_documentation_query_appends_documentation():
    q = documentation_query("spring-framework", "https://docs.spring.io/old/gone.html")
    assert "https://" not in q
    assert "documentation" in q
    assert "spring" in q
    assert "gone" in q


def test_filters_wikipedia_yahoo_and_gemini():
    hits = [
        {"url": "https://en.wikipedia.org/wiki/Java", "title": "Java"},
        {"url": "https://search.yahoo.com/search?p=java", "title": "Yahoo"},
        {"url": "https://search.brave.com/search?q=java", "title": "Brave"},
        {"url": "https://www.startpage.com/sp/search", "title": "Startpage"},
        {"url": "https://www.mojeek.com/search?q=java", "title": "Mojeek"},
        {"url": "https://www.google.com/search?q=java", "title": "AI Overview generated by Gemini"},
        {"url": "https://docs.oracle.com/javase/21/docs/api/", "title": "Java API"},
    ]
    kept = filter_search_hits(hits)
    assert len(kept) == 1
    assert "oracle" in kept[0]["url"]


def test_gemini_share_url_is_unusable():
    assert is_unusable_hit("https://gemini.google.com/app", "Gemini", "Gemini said")


def test_rank_prefers_official_docs():
    hits = [
        {"url": "https://medium.com/spring-beans", "title": "beans tutorial"},
        {"url": "https://docs.spring.io/spring-framework/reference/core/beans.html", "title": "beans"},
    ]
    ranked = rank_search_hits(hits, keywords="spring beans", preferred_host="docs.spring.io")
    assert ranked[0]["url"].startswith("https://docs.spring.io/")


def test_ddgs_uses_single_engine_never_auto_or_google(settings, monkeypatch):
    settings.tavily_api_key = None
    settings.brave_api_key = None
    settings.searxng_url = None
    captured: dict[str, object] = {}

    class _Client:
        def __enter__(self):
            return self

        def __exit__(self, *args):
            return False

        def text(self, query, **kwargs):
            captured["kwargs"] = kwargs
            captured["query"] = query
            return [{
                "title": "beans",
                "href": "https://docs.spring.io/spring-framework/reference/core/beans.html",
                "body": "Spring beans",
            }]

    monkeypatch.setattr("ddgs.DDGS", lambda *a, **k: _Client())
    from mcp_kb.retrieval.web_search import search_web

    hits = search_web("spring beans", settings, limit=3)
    assert hits
    assert captured["kwargs"].get("backend") == "duckduckgo"
    assert captured["kwargs"].get("backend") not in {None, "auto", "all", "google"}


def test_ddgs_skips_when_duckduckgo_disabled(settings, monkeypatch):
    settings.tavily_api_key = None
    settings.brave_api_key = None
    settings.searxng_url = None

    class _Boom:
        def __enter__(self):
            raise AssertionError("ddgs must not run when no configured backend is available")

        def __exit__(self, *args):
            return False

    monkeypatch.setattr("mcp_kb.retrieval.web_search._enabled_ddgs_text_backends", lambda: {"yahoo"})
    monkeypatch.setattr("ddgs.DDGS", lambda *a, **k: _Boom())
    from mcp_kb.retrieval.web_search import search_web

    assert search_web("spring beans", settings, limit=3) == []


def test_ddgs_falls_back_to_next_backend_when_first_fails(settings, monkeypatch):
    settings.tavily_api_key = None
    settings.brave_api_key = None
    settings.searxng_url = None
    calls: list[str] = []

    class _Client:
        def __enter__(self):
            return self

        def __exit__(self, *args):
            return False

        def text(self, query, **kwargs):
            calls.append(kwargs.get("backend"))
            if kwargs.get("backend") == "duckduckgo":
                raise TimeoutError("blocked")
            return [{
                "title": "beans",
                "href": "https://docs.spring.io/spring-framework/reference/core/beans.html",
                "body": "Spring beans",
            }]

    monkeypatch.setattr(
        "mcp_kb.retrieval.web_search._enabled_ddgs_text_backends",
        lambda: {"duckduckgo", "brave"},
    )
    monkeypatch.setattr("ddgs.DDGS", lambda *a, **k: _Client())
    from mcp_kb.retrieval.web_search import search_web

    hits = search_web("spring beans", settings, limit=3)
    assert hits
    assert calls == ["duckduckgo", "brave"]
